{{- $gateway := .Values.gateway }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kgateway.gateway.fullname" . }}
  {{- with (($gateway.serviceAccount).extraAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kgateway.gateway.constLabels" . | nindent 4 }}
    {{- include "kgateway.gateway.labels" . | nindent 4 }}
    {{- with (($gateway.serviceAccount).extraLabels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
