{{- $gateway := .Values.gateway }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kgateway.gateway.fullname" . }}
  annotations:
    {{- toYaml (merge
      ($gateway.gatewayAnnotations| default dict)
      ((($gateway.serviceAccount).extraAnnotations) | default dict)
    ) | nindent 4 }}
  labels:
    {{- toYaml (merge
      (include "kgateway.gateway.allLabels" . | fromYaml)
      ((($gateway.serviceAccount).extraLabels) | default dict)
    ) | nindent 4 }}
automountServiceAccountToken: false
