apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ai-gateway
spec:
  gatewayClassName: agentgateway
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: unified-ai-backend
spec:
  type: AI
  ai:
    llm:
      anthropic:
        model: claude-sonnet-4-20250514
        authToken:
          kind: SecretRef
          secretRef:
            name: anthropic-secret
      routes:
        "/v1/chat/completions": "completions"
        "/v1/messages": "messages"
        "/v1/models": "models"
        "*": "passthrough"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ai-route
spec:
  parentRefs:
  - name: ai-gateway
  rules:
  - backendRefs:
    - group: gateway.kgateway.dev
      kind: Backend
      name: unified-ai-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-secret
type: Opaque
stringData:
  x-api-key: "sk-ant-your-anthropic-key"
