name: Regression Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

env:
  VERSION: '1.0.0-ci1'
  GITHUB_TOKEN: ${{ github.token }} # necessary to pass upgrade tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  kube_gateway_api_conformance_tests:
    name: kubernetes gateway api conformance tests (${{matrix.image-variant}})
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', kubectl: 'v1.33.2', kind: 'v0.29.0' } ]
        image-variant:
          - standard
    steps:
    - uses: actions/checkout@v4
    - id: run-tests
      uses: ./.github/actions/kube-gateway-api-conformance-tests

  kube_inference_extension_conformance_tests:
    name: kubernetes gateway api inference extension conformance tests (${{matrix.image-variant}})
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', kubectl: 'v1.33.2', kind: 'v0.29.0' } ]
        image-variant:
          - standard
    steps:
    - uses: actions/checkout@v4
    - id: run-tests
      uses: ./.github/actions/kube-inference-extension-conformance-tests

  kube_agent_gateway_conformance_tests:
    name: kubernetes gateway api agent-gateway conformance tests (${{matrix.image-variant}})
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    env:
      CONFORMANCE_GATEWAY_CLASS: agentgateway
      HELM_ADDITIONAL_VALUES: test/kubernetes/e2e/tests/manifests/agent-gateway-integration.yaml
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', kubectl: 'v1.33.2', kind: 'v0.29.0' } ]
        image-variant:
          - standard
    steps:
    - uses: actions/checkout@v4
    - id: run-tests
      uses: ./.github/actions/kube-agent-gateway-conformance-tests
