name: Run Conformance Tests

on:
  # TODO: Trigger on release events too.
  workflow_dispatch:
    inputs:
      version:
        description: "Optional: Specify an existing kgateway release tag to deploy and test. Leave empty to use the default branch."
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run-conformance-tests:
    runs-on: ubuntu-22.04
    env:
      IMAGE_REGISTRY: cr.kgateway.dev/kgateway-dev
    strategy:
      matrix:
        # TODO(tim): Avoid hardcoding versions here. It's a bit tricky based on
        # how this was setup and there's a limited # of dispatch inputs that GH
        # supports. We can revisit this later.
        kube-version:
        - node: 'v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a'
          kubectl: 'v1.34.1'
          kind: 'v0.30.0'
        version:
          - ${{ inputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Conformance Tests
        uses: ./.github/actions/kube-gateway-api-conformance-tests

  run-agent-gateway-conformance-tests:
    runs-on: ubuntu-22.04
    env:
      IMAGE_REGISTRY: cr.kgateway.dev/kgateway-dev
      CONFORMANCE_GATEWAY_CLASS: agentgateway
      HELM_ADDITIONAL_VALUES: test/kubernetes/e2e/tests/manifests/agent-gateway-integration.yaml
    strategy:
      matrix:
        kube-version:
        - node: 'v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a'
          kubectl: 'v1.34.1'
          kind: 'v0.30.0'
        version:
          - ${{ inputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Agent-Gateway Conformance Tests
        uses: ./.github/actions/kube-gateway-api-conformance-tests
