# This workflow parses the PR description to extract the change type and changelog for release notes.
name: PR kind labeler
on:
  pull_request_target:
    types: [opened, edited, reopened]
  merge_group:
    types: [checks_requested]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      # only run this step on PRs, not in the merge queue (we need to explicitly add the merge queue logic because making this check required
      # causes it to get run in the merge queue as well)
      - name: Conditional skip for merge queue
        if: github.event_name == 'merge_group'
        run: |
          echo "Skipping check in merge queue"
          exit 0

      - if: github.event_name != 'merge_group'
        uses: actions/checkout@v4
      - name: Sync /kind labels & enforce changelog fields
        if: github.event_name != 'merge_group'
        uses: kgateway-dev/pr-kind-labeler@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
